### ISSUE TITLE
8大诉求，缺一不可

### ISSUE THREAD

**Issue by n0099** [The-GregTech-Team/Thinking-on-Mirai#2]
https://github.com/The-GregTech-Team/Anti-Mirai-Compaign

## 运动目标
* [Mirai org（mamoe）](https://github.com/mamoe) 必须解除对 [@dylech30th](https://github.com/dylech30th) 的block。
* `Mirai` 必须移除文档中的不友善内容。不友善的标准由本运动评定。
* `Mirai` 不得非功能性重命名类，方法，参数。Typo除外。
* `Mirai` 可以进行重构，但旧的公开方法不得移除，必须标记为 Deprecated 并在下一个大版本才能移除。必须在文档中提供新的使用方式。
* `Mirai` 可以开放赞助，但不得禁止非赞助用户使用，不得歧视未赞助用户。并且在文档中移除所有歧视商业用户的行为。违反腾讯用户协议的除外。
* `Mirai-console` 不得进行强制自动更新。
* 以上任何一条目标未达成，本运动将继续进行。我们使用**和平手段**抗议。

**Comment by Him188** [comment]
既然看到了我况且回复一下。

> Mirai必须移除文档中的不友善内容。不友善的标准由本运动评定。

你可以去看现在的文档

> Mirai不得非功能性重命名类，方法，参数。Typo 除外。

2.0-RC 稳定版本起本来就不会修改了 [版本规范](https://github.com/mamoe/mirai/blob/dev/docs/Evolution.md#%E7%89%88%E6%9C%AC%E8%A7%84%E8%8C%83)  
1.0 -> 1.3.3 的更新过程也一直没有出二进制不兼容的改变.  
唯一的改变是 2.0-Mx 重构版本, 然而我把它发布为 "pre-release" 并声明没有兼容性保障.  

> Mirai可以进行重构，但旧的公开方法不得移除，必须标记为Deprecated 并在下一个大版本才能移除。必须在文档中提供新的使用方式。

1.0 -> 2.0 还不算大版本吗? 现在的文档已经很全面而且有 https://github.com/mamoe/mirai/discussions/848 , 每个弃用都提供了 `@Deprecated` 或在 release note 提供了迁移说明

1.0 -> 1.3.3 没有发生破坏性二进制变更  
2.0 起 mirai 制定兼容性策略 [更新兼容性](https://github.com/mamoe/mirai/blob/dev/docs/Evolution.md#%E6%9B%B4%E6%96%B0%E5%85%BC%E5%AE%B9%E6%80%A7) 并且强调会有永久的二进制向后兼容和至少两个版本的源码兼容

> Mirai可以开放赞助，但不得禁止非赞助用户使用，不得歧视未赞助用户。并且在文档中移除所有歧视商业用户的行为。违反腾讯用户协议的除外。

文档没有歧视商业用户

> Miraiconsole不得进行强制自动更新。

mirai console 目前只是一个没有入口的框架. mirai-console-loader 会根据用户设置决定是否更新.

**Comment by takayama-lily** [comment]
打广告，Node.js玩家可以使用此项目哦
https://github.com/takayama-lily/oicq

**Comment by ishkong** [comment]
打广告，Python玩家可以使用此项目哦
https://github.com/nonebot/nonebot2

**Comment by Mrs4s** [comment]
打个广告, Go玩家可以使用此项目哦
https://github.com/Mrs4s/MiraiGo
甚至没有版本号, 免除你看到版本号就ptsd的担忧

**Comment by Yiwen-Chan** [comment]
打个广告，易语言玩家可以使用此项目哦
https://www.xianqubot.com/
甚至不开源，免除你看到代码就血压爆炸

**Comment by synodriver** [comment]
[打个广告, python玩家可以使用此项目哦,完全由py实现的协议](https://github.com/synodriver/pymirai)

**Comment by 3535772662** [comment]
大傻逼
