### ISSUE TITLE
反 him188 文档中的不合理之处和引申

### ISSUE THREAD

**Issue by StageGuard** [The-GregTech-Team/Thinking-on-Mirai#3]
![Screenshot_2021-01-12-23-44-08-968_com tencent mobileqq](https://user-images.githubusercontent.com/45701251/104337423-71256780-5530-11eb-9dbb-0c17792b6415.jpg)

mirai 已经声明 2.0-Mx 版本不会保证兼容性，如果寻求稳定可以使用 1.3.3。
但是 mirai 是否能正常使用还是取决于txqq是否发生了变化。比如，最近很多人一直被 禁止登录，上网异常 和 升级QQ版本 的问题困扰，就是因为txqq的协议(或者说不可抗力因素)发生了变化而导致的，mirai 维护者在 2.0-M2 修复了这个致命问题。

那么使用 core 1.3.3 出现这个问题的用户怎么办，为了他们而维护 1.3.3版本吗？似乎可以，但其实并不可以。随着时间推移，这种txqq协议的变化肯定会更多，而 1.3.3 代码的结构很糟糕(him188承认的)，比起再花时间对"旧的糟糕的"代码，专注于 2.0 的设计会是更好的选择。

上图说 mysql 5.7 可以用一辈子，因为使用它没有致命性约束因素，而 mirai 是有致命性约束因素的(上文提到的txqq协议变化)。就像我在图里说的，你能用 qqweb 一辈子吗？

**Comment by LasmGratel** [comment]
你说的致命问题：
根据https://github.com/mamoe/mirai/issues/772，腾讯添加了滑动验证码，因此旧版本无法登陆而2.0-M2-dev-9新版可以登录
根据
https://github.com/mamoe/mirai/issues/797
2.0-RC-dev-1开始图裂问题才被修复

但是在这些协议的更改下架构在fast-forward大变革，这难道不是在强迫开发者一次又一次移植到最新版本？或者说mirai的开发周期在协议的不断变动下存在大问题？在架构进行大变动的同时有没有照顾到旧版本的开发者？

**Comment by LasmGratel** [comment]
我觉得一个略有经验的开发者都知道不要轻易修改公共接口的重要性吧。如果我想做一个reply功能都要在2.0版本有着各种写法，我很难想到mirai的整体设计是否真的存在一个目标

**Comment by LasmGratel** [comment]
协议当然一直在更新，可是QQ的基本功能变了吗？既然没有变，为什么每次都要在基本的聊天和回复功能上各种大改，从MessageEvent的reply变成dsl，从File变成ExternalResource，并且毫不兼容旧代码老代码？
所以我对2.0持悲观态度也在于此，在这些基础聊天功能上进行多次大改很明显就能说明2.0是没有一个清晰的代码逻辑的。

**Comment by StageGuard** [comment]
> 你说的致命问题：
> 根据[https://github.com/mamoe/mirai/issues/772，腾讯添加了滑动验证码，因此旧版本无法登陆而2.0-M2-dev-9新版可以登录](https://github.com/mamoe/mirai/issues/772%EF%BC%8C%E8%85%BE%E8%AE%AF%E6%B7%BB%E5%8A%A0%E4%BA%86%E6%BB%91%E5%8A%A8%E9%AA%8C%E8%AF%81%E7%A0%81%EF%BC%8C%E5%9B%A0%E6%AD%A4%E6%97%A7%E7%89%88%E6%9C%AC%E6%97%A0%E6%B3%95%E7%99%BB%E9%99%86%E8%80%8C2.0-M2-dev-9%E6%96%B0%E7%89%88%E5%8F%AF%E4%BB%A5%E7%99%BB%E5%BD%95)
> 根据
> [mamoe/mirai#797](https://github.com/mamoe/mirai/issues/797)
> 2.0-RC-dev-1开始图裂问题才被修复
> 
> 但是在这些协议的更改下架构在fast-forward大变革，这难道不是在强迫开发者一次又一次移植到最新版本？或者说mirai的开发周期在协议的不断变动下存在大问题？在架构进行大变动的同时有没有照顾到旧版本的开发者？
@LasmGratel 
对于强迫迁移：
mirai 的开发周期并没有问题，现阶段处于快速变革时期的 mirai 为不稳定版本。
mirai 并没有强迫迁移新版的行为，只是正好协议的致命变化在框架大变革时期，这其实是一个"偶然"。而比起维护 1.3.3 的代码，显然专注 2.0 的重构是更好的选择。

对于框架变更：
任何人都不是神仙，一开始就能设计出完美稳定的接口，对于 breaking changes，mirai 在 2.0-Mx 的每一个过渡版本都有相对于上一个版本的迁移提示，并不是直接让你一脸茫然。mirai 的 2.x 版本对于 1.x 版本来说是一次巨大的更新，很难保证完全兼容 1.x，可以说任何框架在大版本更新都很难保证完全兼容(除非分离了旧版)。一昧地兼容只会为以后的开发埋下炸弹。

我觉得你们是带着偏见来的，打一开始就没有平和交流的意图。要是协议没变，旧版依旧能用，大概率估计你们也不会过来长篇大论。

**Comment by StageGuard** [comment]
> 协议当然一直在更新，可是QQ的基本功能变了吗？既然没有变，为什么每次都要在基本的聊天和回复功能上各种大改，从MessageEvent的reply变成dsl，从File变成ExternalResource，并且毫不兼容旧代码老代码？
> 所以我对2.0持悲观态度也在于此，在这些基础聊天功能上进行多次大改很明显就能说明2.0是没有一个清晰的代码逻辑的。

@LasmGratel 
为了以后更容易维护和提升框架使用体验，这种 breaking changes 是必然的，还好早这样了，否则以后回更难。
让你开发框架，你肯定会首先构思使用效果(或者说接口)，构思好了开始写，结果很满意。但是后来发现开发过程中因为一些限制因素，一些接口的实现非常困难，不得不绕个大圈子才能实现，只有更改接口才能使以后的维护更加容易，你会选择标注 @Deprecated 还是为了兼容性保持接口原状。
如果一直 mirai 不放出 2.0-Mx 的过渡版本而直接来一个 RC 版本，我觉得光 release note 的"从 1.3.3 迁移"就得占一大半。
2.0-RC 的 release 已经保证以后的更新会有兼容性保证，这是很不容易的。从 2.0-RC 开始保证兼容性比从 1.3.3 开始保证兼容性要容易得多。

如果你不想迁移，你可以自己 clone 一份 1.3.3 的代码，自己修改适配协议。
如果你想稳定，mirai 可能不是你最好的选择，你可以试试一些商业 QQ 机器人框架。

**Comment by StageGuard** [comment]
> 我觉得一个略有经验的开发者都知道不要轻易修改公共接口的重要性吧。如果我想做一个reply功能都要在2.0版本有着各种写法，我很难想到mirai的整体设计是否真的存在一个目标

版本大变更时改动部分接口方法是合理的。
一个功能有很多种写法是为了可以减少对上下文的依赖，使其更方便使用，虽然写法多，但内部的实现最终都指向了同一个方法。

**Comment by koiNoCirculation** [comment]
一个软件设计的时候就要多考虑需求。
一个聊天机器人需求是什么？
接受来自用户的输入，包括但不限于文字，图片等形式，我可以简单点，限定为文字和图片，以及文字和图片的混搭。
然后向用户返回对应的输出，对吧，和一个http server很类似。
具体到qq这个场景，我们有点对点的聊天和群内聊天（一对一，一堆多），群聊天内可以at圈人来在群中针对某个人进行回复。
对外的接口可以是这样(伪代码)

class Message ----------------- TextMessage
                                    |-------- PictureMessage
                                    |-------- MixedContentMessage
                                    |-------- UnknownTypeMessage
                                    .......................
class Friend ---------- Group


```java
/**
  * 你里面怎么处理我不管，我只看这个接口
  * 怎么登录，怎么接受消息，怎么回复消息都不是我一个外部dev所关心的。
  * 这个作为产品的对外功能，在没有必要的情况下，完全没有必要改变。
  */
public interface QQBot {
      //点对点
      void p2pSend(Message message, String destQQ) throws QQException; 
      //点对群，不@人
      void p2gSend(Message message, String destGroup)  throws QQException;
      //点对群, @人
      void p2gSendWithAt(Message message, String destGroup, String destQQ)  throws QQException;
      Collection<Friend> getMyFriends();
      Collection<Group> getMyGroups();
      Friend getFriend(String qq);
      Group getGroup(String group);
      
      /**
        * 允许级联注册多个receiver？有用么（
        */
      void registerMessageReceiver(QQMessageReceiver receiver);
}

/**
  * 处理qq消息
  */
public interface QQMessageReceiver {
      void receiveMessage(TextMessage message);
      void receivePictureMessage(PictureMessage message);
      void receiveMixedContentMessage(MixedContentMessage message);
      void receiveUnknownTypeMessage(UnknownTypeMessage message)
}
```

我的客户端程序应该是这样的(Spring为例)

```java
//my.qq和my.password在配置里面
@Service
class MyMessageReceiver implements InitializingBean, QQMessageReceiver  {
      @Resource
      QQBot bot;
      @Override
       public void afterPropertiesSet() {
             bot.registerMessageReceiver(this);
       }
       ............
       /*应用程序实现
          年轻人你们还是要学习一个
        */
} 
```


Dependencies:

My application ---------- QQBot-API-X.X -----------QQBot-Impl-X.X-SNAPSHOT

每次升级我只需要换下impl的版本，重新编译上线，这是我们想看到的才对。

**Comment by DazeCake** [comment]
> 一个软件设计的时候就要多考虑需求。
> 一个聊天机器人需求是什么？
> 接受来自用户的输入，包括但不限于文字，图片等形式，我可以简单点，限定为文字和图片，以及文字和图片的混搭。
> 然后向用户返回对应的输出，对吧，和一个http server很类似。
> 具体到qq这个场景，我们有点对点的聊天和群内聊天（一对一，一堆多），群聊天内可以at圈人来在群中针对某个人进行回复。
> 对外的接口可以是这样(伪代码)
> 
> class Message ----------------- TextMessage
>                                     |-------- PictureMessage
>                                     |-------- MixedContentMessage
>                                     |-------- UnknownTypeMessage
>                                     .......................
> class Friend ---------- Group
> 
> 
> ```java
> /**
>   * 你里面怎么处理我不管，我只看这个接口
>   * 怎么登录，怎么接受消息，怎么回复消息都不是我一个外部dev所关心的。
>   * 这个作为产品的对外功能，在没有必要的情况下，完全没有必要改变。
>   */
> public interface QQBot {
>       //点对点
>       void p2pSend(Message message, String destQQ) throws QQException; 
>       //点对群，不@人
>       void p2gSend(Message message, String destGroup)  throws QQException;
>       //点对群, @人
>       void p2gSendWithAt(Message message, String destGroup, String destQQ)  throws QQException;
>       Collection<Friend> getMyFriends();
>       Collection<Group> getMyGroups();
>       Friend getFriend(String qq);
>       Group getGroup(String group);
>       
>       /**
>         * 允许级联注册多个receiver？有用么（
>         */
>       void registerMessageReceiver(QQMessageReceiver receiver);
> }
> 
> /**
>   * 处理qq消息
>   */
> public interface QQMessageReceiver {
>       void receiveMessage(TextMessage message);
>       void receivePictureMessage(PictureMessage message);
>       void receiveMixedContentMessage(MixedContentMessage message);
>       void receiveUnknownTypeMessage(UnknownTypeMessage message)
> }
> ```
> 
> 我的客户端程序应该是这样的(Spring为例)
> 
> ```java
> //my.qq和my.password在配置里面
> @Service
> class MyMessageReceiver implements InitializingBean, QQMessageReceiver  {
>       @Resource
>       QQBot bot;
>       @Override
>        public void afterPropertiesSet() {
>              bot.registerMessageReceiver(this);
>        }
>        ............
>        /*应用程序实现
>           年轻人你们还是要学习一个
>         */
> } 
> ```
> 
> 
> Dependencies:
> 
> My application ---------- QQBot-API-X.X -----------QQBot-Impl-X.X-SNAPSHOT
> 
> 每次升级我只需要换下impl的版本，重新编译上线，这是我们想看到的才对。

你不想花费很大成本来适配mirai更新所造成的麻烦，我觉得可以理解，但是因此去谴责去声讨我觉得是不合适的，在你的观点里我感受到的是“我不管你怎么搞，总之我就是要用，要稳定的用，最好tx的协议变了mirai的接口也不能变”（如果我的理解有误请指出），我是否可以认为里面包含了私心呢？因为如果只是一个外部dev单纯的要实现你的功能需求，mirai也是给出了http-api作为解决方案的，他是可以完全实现需求的。这就导致了这场所谓运动最最根本的论点就站不住脚。

**Comment by koiNoCirculation** [comment]
@DazeCake 我认为恰恰相反，mirai-http-api正说明了原开发者水平的不靠谱，如果原开发者有能力做一个封装，那为什么还要增加一个mirai-http-api实体？直接各语言给接口不就完事了？mirai-http-api需要多引入一个实体，多跑一个console，这不好。mirai-http-api作为一个中间人的角色，本不该存在，是为了给水平不行的开发擦屁股诞生的，我这么理解。

**Comment by StageGuard** [comment]
> @DazeCake 我认为恰恰相反，mirai-http-api正说明了原开发者水平的不靠谱，如果原开发者有能力做一个封装，那为什么还要增加一个mirai-http-api实体？直接各语言给接口不就完事了？mirai-http-api需要多引入一个实体，多跑一个console，这不好。mirai-http-api作为一个中间人的角色，本不该存在，是为了给水平不行的开发擦屁股诞生的，我这么理解。

mirai-http-api 是为了让非JVM语言使用而诞生的

**Comment by koiNoCirculation** [comment]
@DazeCake 如果原生语言的开发者都要被逼得去用这个东西，是不是说明底层不靠谱？miraihttp或许是靠谱的，但不代表本体就靠谱。如果原生的接口就设计的得当，那多好呢，对吧。

**Comment by koiNoCirculation** [comment]
@DazeCake 各语言理解是有点问题，可是为什么原生jvm上搞我还要搞微服务？这就是单机应用而已。我还能给整个前端负载均衡，后端服务化么？

**Comment by StageGuard** [comment]
> @DazeCake 各语言理解是有点问题，可是为什么原生jvm上搞我还要搞微服务？这就是单机应用而已。我还能给整个前端负载均衡，后端服务化么？

所以你想要什么效果？把mirai用每一种语言都写一遍吗？你来吗？

**Comment by StageGuard** [comment]
> @DazeCake 各语言理解是有点问题，可是为什么原生jvm上搞我还要搞微服务？这就是单机应用而已。我还能给整个前端负载均衡，后端服务化么？

构建 http/websocket 服务是让其他语言也能使用mirai的最佳选择，如果你有更好的方案，可以告诉我

**Comment by DazeCake** [comment]
> @DazeCake 我认为恰恰相反，mirai-http-api正说明了原开发者水平的不靠谱，如果原开发者有能力做一个封装，那为什么还要增加一个mirai-http-api实体？直接各语言给接口不就完事了？mirai-http-api需要多引入一个实体，多跑一个console，这不好。mirai-http-api作为一个中间人的角色，本不该存在，是为了给水平不行的开发擦屁股诞生的，我这么理解。

我明白你的意思，你的意思是说mirai的作者水平不行，没有达到你的标准，既然如此我认为比起在这里抱怨这的那的，不如参与mirai的开发，提交pr，以此来符合你要求的标准，但事实上似乎并没有任何一条pr。正如那句著名的格言
> 如果你觉得你的祖国不好，你就去建设它；如果你觉得政府不好，你就去考公务员去做官；如果你觉得人民没素质，就从你开始做一个高素质的公民；如果你觉得同胞愚昧无知，就从你开始学习并改变身边的人，而不是一味的谩骂、抱怨、逃离。

所有我也觉得，如果你觉得mirai-core不好，那么就去pr他，而不是一味的谩骂、抱怨、逃离。

**Comment by koiNoCirculation** [comment]
@DazeCake 我指的当然是让jvm上的语言不要走微服务，你看，理解偏差了吧，扣分。
我觉得稍有软开知识的人都能做到。
况且我不是使用者，我也会尽量避免和这种天天在需求没有大变更的情况下改接口的同事工作，给他改代码我不拿工资，天天还增加我的工作量。
这样的人要是跟我一组，我会选择尽量不跟他做一个项目，或者想办法让leader给他压力。
我本来也挺忙，半夜不回家来这对线也是看我群友那副被折磨的样子不爽而已。

**Comment by koiNoCirculation** [comment]
@DazeCake 我自己没有qq机器人的需求，真有的话，我恐怕也不会选mirai的，哈哈。有可能真就自己整个自己用。

**Comment by StageGuard** [comment]
> @DazeCake 我指的当然是让jvm上的语言不要走微服务，你看，理解偏差了吧，扣分。
> 我觉得稍有软开知识的人都能做到。
> 况且我不是使用者，我也会尽量避免和这种天天在需求没有大变更的情况下改接口的同事工作，给他改代码我不拿工资，天天还增加我的工作量。
> 这样的人要是跟我一组，我会选择尽量不跟他做一个项目，或者想办法让leader给他压力。
> 我本来也挺忙，半夜不回家来这对线也是看我群友那副被折磨的样子不爽而已。

@koiNoCirculation 你可以告诉我怎么“不让jvm语言走微服务来让其他语言使用mirai”吗？
如果不能提出建议，请你闭嘴。

**Comment by koiNoCirculation** [comment]
@StageGuard 重点是原生语言不走http，看清重点。
原生语言的开发能被你们这帮折磨王给折磨到用http，你们可真是人才。

**Comment by StageGuard** [comment]
> @StageGuard 重点是原生语言不走http，看清重点。
> 原生语言的开发能被你们这帮折磨王给折磨到用http，你们可真是人才。

你可以告诉我怎么让原生语言直接使用jvm的接口吗？
如果不能，请你闭嘴

**Comment by koiNoCirculation** [comment]
@DazeCake 呵呵，看看我上面的回复，java interface，你只要不随便改设计接口，谁会起微服务？

**Comment by koiNoCirculation** [comment]
@DazeCake jvm的原生语言，java，kt，scala等。你要是能理解成c我只能说，阅读有问题。

**Comment by StageGuard** [comment]
> @DazeCake jvm的原生语言，java，kt，scala等。你要是能理解成c我只能说，阅读有问题。

我告诉你，http服务是给其他非jvm语言使用的，不是给jvm语言使用的。

**Comment by koiNoCirculation** [comment]
@DazeCake 重点是，原生语言都要转用http套一层，你们原本的接口要多糟糕才能逼人这样？哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈。

**Comment by DazeCake** [comment]
> @DazeCake 我指的当然是让jvm上的语言不要走微服务，你看，理解偏差了吧，扣分。
> 我觉得稍有软开知识的人都能做到。
> 况且我不是使用者，我也会尽量避免和这种天天在需求没有大变更的情况下改接口的同事工作，给他改代码我不拿工资，天天还增加我的工作量。
> 这样的人要是跟我一组，我会选择尽量不跟他做一个项目，或者想办法让leader给他压力。
> 我本来也挺忙，半夜不回家来这对线也是看我群友那副被折磨的样子不爽而已。

你也说了

> 我会选择尽量不跟他做一个项目

那么前路十分光明的，可以选择使用其他框架，而不是来到这里发泄情绪，埋怨和指责。因为这里并不存在拿工资一说，mamoe work for love 没有理由接受你的
> 不爽而已

所以我依旧保留我的观点，你也可以坚持你的看法

**Comment by StageGuard** [comment]
> > @DazeCake jvm的原生语言，java，kt，scala等。你要是能理解成c我只能说，阅读有问题。
> 
> 我告诉你，http服务是给其他非jvm语言使用的，不是给jvm语言使用的。



> @DazeCake 重点是，原生语言都要转用http套一层，你们原本的接口要多糟糕才能逼人这样？哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈。

你哪只眼睛看见原生眼睛转用http服务了？

**Comment by koiNoCirculation** [comment]
@DazeCake yes，我只是帮我群友说说。
可能过几天我就忘记了吧，嗯，因为我不用，我很快就能忘了。
更烂的项目多了去了，比如minecraft，每个版本都变，但是人家是商业软件，我也有选择1.7.10的权利，233.

**Comment by StageGuard** [comment]
> 更烂的项目多了去了，比如minecraft，每个版本都变，但是人家是商业软件，我也有选择1.7.10的权利，233.

@koiNoCirculation 我已经不想解释这一点了，你去翻这个issue最开头的那几个回复吧

**Comment by koiNoCirculation** [comment]
@StageGuard 看了你们那个四个泛型的东西我就想吐，我一定会选择http的，哦吼~
选http至少可以把臭味给压住，选原生那就是在恰奥里给。

**Comment by StageGuard** [comment]
> @StageGuard 看了你们那个四个泛型的东西我就想吐，我一定会选择http的，哦吼~
> 选http至少可以把臭味给压住，选原生那就是在恰奥里给。

原生使用者并不需要了解那四个泛型，那是接口内部的实现。
当然如果你想了解，等你有了坚实的kotlin基础再了解。

**Comment by koiNoCirculation** [comment]
@DazeCake httpapi我粗读了下，没有泛型，没有乱七八糟的什么东西对外，至少是个可用的东西，如果是我的话我肯定也会选http。

**Comment by StageGuard** [comment]
@koiNoCirculation 小鬼给爷爬。
unsubscribe this notification.
恁就自娱自乐吧

**Comment by TheRealKamisama** [comment]
> 
> 
> > @DazeCake 我认为恰恰相反，mirai-http-api正说明了原开发者水平的不靠谱，如果原开发者有能力做一个封装，那为什么还要增加一个mirai-http-api实体？直接各语言给接口不就完事了？mirai-http-api需要多引入一个实体，多跑一个console，这不好。mirai-http-api作为一个中间人的角色，本不该存在，是为了给水平不行的开发擦屁股诞生的，我这么理解。
> 
> 我明白你的意思，你的意思是说mirai的作者水平不行，没有达到你的标准，既然如此我认为比起在这里抱怨这的那的，不如参与mirai的开发，提交pr，以此来符合你要求的标准，但事实上似乎并没有任何一条pr。正如那句著名的格言
> 
> > 如果你觉得你的祖国不好，你就去建设它；如果你觉得政府不好，你就去考公务员去做官；如果你觉得人民没素质，就从你开始做一个高素质的公民；如果你觉得同胞愚昧无知，就从你开始学习并改变身边的人，而不是一味的谩骂、抱怨、逃离。
> 
> 所有我也觉得，如果你觉得mirai-core不好，那么就去pr他，而不是一味的谩骂、抱怨、逃离。

![QQ图片20210114113538.png](https://i.loli.net/2021/01/14/ZsTMbJ3xr54cLoV.png)

**Comment by koiNoCirculation** [comment]
@StageGuard 如果人家只需要调接口就好了，谁tm的关心你有几个泛型？谁想关心你kotlin基础有多好？
说白了，让人需要翻你的代码看你的内部实现才能做功能，你的封装，你的屏蔽细节，已经失败了，你的软件从设计层面就是失败作。
哦对了，你应该unsubscribe了，那拜拜。

**Comment by StageGuard** [comment]
> @StageGuard 如果人家只需要调接口就好了，谁tm的关心你有几个泛型？谁想关心你kotlin基础有多好？
> 说白了，让人需要翻你的代码看你的内部实现才能做功能，你的封装，你的屏蔽细节，已经失败了，你的软件从设计层面就是失败作。
> 哦对了，你应该unsubscribe了，那拜拜。

哦对了，最后说一句，你不需要了解那些泛型也可以使用，通过 [`subscribeMessages {}`](https://github.com/mamoe/mirai/blob/dev/docs/Events.md#%E5%9C%A8-kotlin-%E4%BD%BF%E7%94%A8-dsl-%E7%9B%91%E5%90%AC%E4%BA%8B%E4%BB%B6)
况且并没有强制要求你了解，你只要会用就行。
前提是你要有坚实的kotlin基础哦！

一想到 你在绞尽脑汁想怎么喷我的 时候，我我就觉得特别好玩。
你们喷子都有一个共同特点：就是喜欢拿 同事工作 这类的例子来比喻。
我告诉你，mirai与你无冤无仇，你不使用它，你又觉得它糟糕，这很ok，不要接触它，不要看它，让它从你的视野消失。
如果你是受人委托过来喷的话，那你只是一个被别人操控的可怜小丑罢了。
blocked

**Comment by crab-in-the-northeast** [comment]
端起碗吃饭，放下碗骂娘

**Comment by dylech30th** [comment]
> > @StageGuard 如果人家只需要调接口就好了，谁tm的关心你有几个泛型？谁想关心你kotlin基础有多好？
> > 说白了，让人需要翻你的代码看你的内部实现才能做功能，你的封装，你的屏蔽细节，已经失败了，你的软件从设计层面就是失败作。
> > 哦对了，你应该unsubscribe了，那拜拜。
> 
> 哦对了，最后说一句，你不需要了解那些泛型也可以使用，通过 [`subscribeMessages {}`](https://github.com/mamoe/mirai/blob/dev/docs/Events.md#%E5%9C%A8-kotlin-%E4%BD%BF%E7%94%A8-dsl-%E7%9B%91%E5%90%AC%E4%BA%8B%E4%BB%B6)
> 况且并没有强制要求你了解，你只要会用就行。
> 前提是你要有坚实的kotlin基础哦！
> 
> 一想到 你在绞尽脑汁想怎么喷我的 时候，我我就觉得特别好玩。
> 你们喷子都有一个共同特点：就是喜欢拿 同事工作 这类的例子来比喻。
> 我告诉你，mirai与你无冤无仇，你不使用它，你又觉得它糟糕，这很ok，不要接触它，不要看它，让它从你的视野消失。
> 如果你是受人委托过来喷的话，那你只是一个被别人操控的可怜小丑罢了。
> blocked
我可以很有保证的告诉你另外两个人的Kotlin基础非常坚实

**Comment by dylech30th** [comment]
> > > @StageGuard 如果人家只需要调接口就好了，谁tm的关心你有几个泛型？谁想关心你kotlin基础有多好？
> > > 说白了，让人需要翻你的代码看你的内部实现才能做功能，你的封装，你的屏蔽细节，已经失败了，你的软件从设计层面就是失败作。
> > > 哦对了，你应该unsubscribe了，那拜拜。
> > 
> > 
> > 哦对了，最后说一句，你不需要了解那些泛型也可以使用，通过 [`subscribeMessages {}`](https://github.com/mamoe/mirai/blob/dev/docs/Events.md#%E5%9C%A8-kotlin-%E4%BD%BF%E7%94%A8-dsl-%E7%9B%91%E5%90%AC%E4%BA%8B%E4%BB%B6)
> > 况且并没有强制要求你了解，你只要会用就行。
> > 前提是你要有坚实的kotlin基础哦！
> > 一想到 你在绞尽脑汁想怎么喷我的 时候，我我就觉得特别好玩。
> > 你们喷子都有一个共同特点：就是喜欢拿 同事工作 这类的例子来比喻。
> > 我告诉你，mirai与你无冤无仇，你不使用它，你又觉得它糟糕，这很ok，不要接触它，不要看它，让它从你的视野消失。
> > 如果你是受人委托过来喷的话，那你只是一个被别人操控的可怜小丑罢了。
> > blocked

我可以很有保证的告诉你另外两个人的Kotlin基础非常坚实，而且不要尝试随意猜测别人是不是“受人委托”，在扣帽子以前最好给出坚实的证据

**Comment by StageGuard** [comment]
> > > > @StageGuard 如果人家只需要调接口就好了，谁tm的关心你有几个泛型？谁想关心你kotlin基础有多好？
> > > > 说白了，让人需要翻你的代码看你的内部实现才能做功能，你的封装，你的屏蔽细节，已经失败了，你的软件从设计层面就是失败作。
> > > > 哦对了，你应该unsubscribe了，那拜拜。
> > > 
> > > 
> > > 哦对了，最后说一句，你不需要了解那些泛型也可以使用，通过 [`subscribeMessages {}`](https://github.com/mamoe/mirai/blob/dev/docs/Events.md#%E5%9C%A8-kotlin-%E4%BD%BF%E7%94%A8-dsl-%E7%9B%91%E5%90%AC%E4%BA%8B%E4%BB%B6)
> > > 况且并没有强制要求你了解，你只要会用就行。
> > > 前提是你要有坚实的kotlin基础哦！
> > > 一想到 你在绞尽脑汁想怎么喷我的 时候，我我就觉得特别好玩。
> > > 你们喷子都有一个共同特点：就是喜欢拿 同事工作 这类的例子来比喻。
> > > 我告诉你，mirai与你无冤无仇，你不使用它，你又觉得它糟糕，这很ok，不要接触它，不要看它，让它从你的视野消失。
> > > 如果你是受人委托过来喷的话，那你只是一个被别人操控的可怜小丑罢了。
> > > blocked
> 
> 我可以很有保证的告诉你另外两个人的Kotlin基础非常坚实，而且不要尝试随意猜测别人是不是“受人委托”，在扣帽子以前最好给出坚实的证据

它的kotlin水平如何我无法仅从对话得知，但是：
> 重点是，原生语言都要转用http套一层，你们原本的接口要多糟糕才能逼人这样？哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈。

它说的这句话有依据吗？它根本不知道 mirai-api-http 是干什么的，这是胡乱定论吗？
我让它举个具体的例子，它也没有回复我。
我质疑了它很多对 DazeCake 的回复，但它基本没回复我。

**Comment by dylech30th** [comment]
> > > > > @StageGuard 如果人家只需要调接口就好了，谁tm的关心你有几个泛型？谁想关心你kotlin基础有多好？
> > > > > 说白了，让人需要翻你的代码看你的内部实现才能做功能，你的封装，你的屏蔽细节，已经失败了，你的软件从设计层面就是失败作。
> > > > > 哦对了，你应该unsubscribe了，那拜拜。
> > > > 
> > > > 
> > > > 哦对了，最后说一句，你不需要了解那些泛型也可以使用，通过 [`subscribeMessages {}`](https://github.com/mamoe/mirai/blob/dev/docs/Events.md#%E5%9C%A8-kotlin-%E4%BD%BF%E7%94%A8-dsl-%E7%9B%91%E5%90%AC%E4%BA%8B%E4%BB%B6)
> > > > 况且并没有强制要求你了解，你只要会用就行。
> > > > 前提是你要有坚实的kotlin基础哦！
> > > > 一想到 你在绞尽脑汁想怎么喷我的 时候，我我就觉得特别好玩。
> > > > 你们喷子都有一个共同特点：就是喜欢拿 同事工作 这类的例子来比喻。
> > > > 我告诉你，mirai与你无冤无仇，你不使用它，你又觉得它糟糕，这很ok，不要接触它，不要看它，让它从你的视野消失。
> > > > 如果你是受人委托过来喷的话，那你只是一个被别人操控的可怜小丑罢了。
> > > > blocked
> > 
> > 
> > 我可以很有保证的告诉你另外两个人的Kotlin基础非常坚实，而且不要尝试随意猜测别人是不是“受人委托”，在扣帽子以前最好给出坚实的证据
> 
> 它的kotlin水平如何我无法仅从对话得知，但是：
> 
> > 重点是，原生语言都要转用http套一层，你们原本的接口要多糟糕才能逼人这样？哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈。
> 
> 它说的这句话有依据吗？它根本不知道 mirai-api-http 是干什么的，这是胡乱定论吗？
> 我让它举个具体的例子，它也没有回复我。
> 我质疑了它很多对 DazeCake 的回复，但它基本没回复我。
> 它又说了他不是 mirai 使用者，那它为什么要对 DazeCake 和 mirai 恶言相向？
> 
> 以上，我可以很明确地断定他就是过来喷的。

那你如何看待隔壁我对你问题的答案呢

**Comment by notnotype** [comment]
考古
