### ISSUE TITLE
建议拆分 [反Him188] 与 [反mirai work style]

### ISSUE THREAD

**Issue by liujiahua123123** [The-GregTech-Team/Thinking-on-Mirai#4]
根据文章内容, 建议将内容分为
对Him188个体的意见 与 对Mirai维护方式的建议

这可以避免对Mirai维护方式中添加不必要的情绪因素，更适用于讨论。

另 以与 提出DSL问题被block的开发者取得联系, 并认为是由于语言传播的信息损失导致的信息不对等，使聆听方获得与叙述方想表达意思与情绪不准确的理解

对于项目维护者们的意见 应当归于[反mirai work style] 而不是全部归于其中一位维护者

**Comment by LasmGratel** [comment]
你说得很对。

**Comment by liujiahua123123** [comment]
那么建议尽快对内容进行更改，以能进行更有效的讨论。

**Comment by liujiahua123123** [comment]
感谢更改, 一切技术讨论均不应该带有对开发者的偏见, 祝好。
